#!/bin/sh
#/
#/ NAME:
#/ repo-reaper - For a GitHub Enterprise Instance, lists every empty repository
#/ in format <organization>:<repository> and deletes them if option is passed.
#/
#/ SYNOPSIS:
#/ repo-reaper [--execute=TRUE]
#/
#/ DESCRIPTION:
#/ For a GitHub Enterprise Instance, lists every empty repository in format
#/ <organization>:<repository> separated by new lines. Deleting them if passed
#/ the option [--execute=true] is passed
#/   - Example Output: List all empty repositories
#/     <organization1>:<repository1>
#/     <organization1>:<repository2>
#/     <organization3>:<repository1>
#/
#/ PRE-REQUISITES:
#/ Before running this script, you must create a Personal Access Token (PAT)
#/ at https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/
#/ with the permissions <repo> and <admin:org> scopes and <delete_repo>. Read more
#/ about scopes here: https://developer.github.com/apps/building-oauth-apps/scopes-for-oauth-apps/
#/
#/ Once created, you must export your PAT as an environment variable
#/ named <GITHUB_TOKEN>.
#/   - Exporting PAT as GITHUB_TOKEN
#/   $ export GITHUB_TOKEN=abcd1234efg567
#/
#/ Additionally you will need to set the $API_ROOT at the top of the script to
#/ your instance of GitHub Enterprise.
#/  - _i.e._: https://MyGitHubEnterprise.com/api/v3
#/
#/ OPTIONS:
#/ --execute
#/ -e
#/ When running the tool, this flag will delete every repo listed.
#/   * _NOTE:_ You should run the script without this option first, verifying
#/      that you want to delete every repository listed.
#/
#/ EXAMPLES:
#/
#/   - Lists all empty repositories for each org that are empty.
#/   $ bash repo-reaper
#/
#/   - Lists all empty repositories for each org that are empty and deletes them.
#/   $ bash repo-reaper --execute=TRUE
#/
#/ API DOCUMENTATION:
#/ All documentation can be found at https://developer.github.com/v3/

# Parse options/flags passed in.
for param in "$@"
do
  case $param in
    -e=*|--execute=*)
    EXECUTE="${param#*=}"
    shift
    ;;
    -o=*|--org=*)
    ORG_NAME="${param#*=}"
    shift
    ;;
    *)
    # unknown option, do nothing
    ;;
  esac
done

API_ROOT="https://<your-domain>/api/v3"
EXECUTE="FALSE"

# Verify Inputs

# If ORG_NAME wasn't passed
if [[ -z ${ORG_NAME} ]]; then
  echo "ERROR: ORG_NAME was not provided."
  echo "  Ex: bash repo-reaper --org=MyOrganization --execute=TRUE"
  echo ""
  echo "Exiting script with no changes."
  echo ""
  exit 1
fi

# If EXECUTE exists, needs to equal TRUE or FALSE
if [[ ${EXECUTE} != "TRUE" ]] && [[ ${EXECUTE} != "FALSE" ]]; then
    echo "ERROR: EXECUTE was not set to a proper value."
    echo "  Ex: bash repo-reaper --org=MyOrganization --execute=TRUE"
    echo ""
    echo "Exiting script with no changes."
    echo ""
    exit 1
fi

##################################################
# Grab JSON of all repositories for organization #
##################################################
REPO_RESPONSE="$(curl --request GET \
--url ${API_ROOT}/orgs/${ORG_NAME}/repos \
-s \
--header "authorization: Bearer ${GITHUB_TOKEN}" \
--header "content-type: application/json")"

##########################################################################
# Loop through every organization's repo to get repository name and size #
##########################################################################
for repo in $(echo "${REPO_RESPONSE}" | jq -r '.[] | @base64');
do
  #####################################
  # Get the info from the json object #
  #####################################
  get_repo_info()
  {
    echo ${repo} | base64 --decode --ignore-garbage | jq -r ${1}
  }

  # Get the info from the JSON object
  REPO_NAME=$(get_repo_info '.name')
  REPO_SIZE=$(get_repo_info '.size')

  # If repository has data, size will not be zero, therefore skip.
  if [[ ${REPO_SIZE} -ne 0 ]]; then
    continue;
  fi

  ################################################
  # If we are NOT deleting repository, list them #
  ################################################
  if [[ ${EXECUTE} = "FALSE" ]]; then
    echo "${ORG_NAME}:${REPO_NAME}"

  #################################################
  # EXECUTE is TRUE, we are deleting repositories #
  #################################################
  elif [[ ${EXECUTE} = "TRUE" ]]; then
      echo "${REPO_NAME} will be deleted from ${ORG_NAME}!"

      ############################
      # Call API to delete repos #
      ############################
      curl --request DELETE \
         --url ${API_ROOT}/repos/${ORG_NAME}/${REPO_NAME} \
         --header "authorization: Bearer ${GITHUB_TOKEN}"
  fi
done
