#!/bin/sh
#/
#/ NAME:
#/ repo-cleaner - For a GitHub Enterprise Instance, lists every empty repository
#/ in format <organization>:<repository> and deletes them if option is passed.
#/
#/ SYNOPSIS:
#/ repo-reaper
#/
#/ DESCRIPTION:
#/ For a GitHub Enterprise Instance, lists every empty repository in format
#/ <organization>:<repository> separated by new lines. Deleting them if passed
#/ the option --execute=true
#/   - Example Output: List all empty repositories
#/     <organization1>:<repository1>
#/     <organization1>:<repository2>
#/     <organization3>:<repository1>
#/
#/ PRE-REQUISITES:
#/ Before running this script, you must create a Personal Access Token (PAT)
#/ at https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/
#/ with the permissions <repo> and <admin:org> scopes and <delete_repo>. Read more
#/ about scopes here: https://developer.github.com/apps/building-oauth-apps/scopes-for-oauth-apps/
#/
#/ Once created, you must export your PAT as an environment variable
#/ named <GITHUB_TOKEN>.
#/   - Exporting PAT as GITHUB_TOKEN
#/   $ export GITHUB_TOKEN=abcd1234efg567
#/
#/ Additionally you will need to set the $API_ROOT at the top of the script to
#/ your instance of GitHub Enterprise.
#/  - _i.e._: https://MyGitHubEnterprise.com/api/v3
#/
#/ OPTIONS:
#/ --execute
#/ -e
#/ When running the tool, this flag will delete every repo listed.
#/   * _NOTE:_ You should run the script without this option first, verifying
#/      that you want to delete every repository listed.
#/
#/ EXAMPLES:
#/
#/   - Lists all empty repositories for each org that are empty.
#/   $ bash repo-reaper
#/
#/   - Lists all empty repositories for each org that are empty and deletes them.
#/   $ bash repo-reaper --execute=true
#/
#/ API DOCUMENTATION:
#/ All documentation can be found at https://developer.github.com/v3/

# Parse options
for i in "$@"
do
  case $i in
    -e=*|--execute=*)
    EXECUTE="${i#*=}"
    shift
    ;;
    *)
    # unknown option
    ;;
  esac
done

API_ROOT="https://api.github.com"
EXECUTE="FALSE"
